<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnVInzW\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnVInzW/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerEnVInzW.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerEnVInzW\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerEnVInzW\App_KernelProdContainer([
    'container.build_hash' => 'EnVInzW',
    'container.build_id' => '24c20802',
    'container.build_time' => 1589398245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnVInzW');
