<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWrrKWQM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWrrKWQM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWrrKWQM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWrrKWQM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWrrKWQM\App_KernelDevDebugContainer([
    'container.build_hash' => 'WrrKWQM',
    'container.build_id' => '30b3f4c1',
    'container.build_time' => 1589374451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWrrKWQM');
