<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \App\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'imie', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'nazwisko', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'temat', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'message', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'dataUtworzenia', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'status'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'imie', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'nazwisko', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'temat', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'message', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'dataUtworzenia', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getImie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImie', []);

        return parent::getImie();
    }

    /**
     * {@inheritDoc}
     */
    public function setImie(string $imie): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImie', [$imie]);

        return parent::setImie($imie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazwisko(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazwisko', []);

        return parent::getNazwisko();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazwisko(string $nazwisko): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazwisko', [$nazwisko]);

        return parent::setNazwisko($nazwisko);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemat', []);

        return parent::getTemat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemat(string $temat): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemat', [$temat]);

        return parent::setTemat($temat);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage(string $message): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataUtworzenia(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataUtworzenia', []);

        return parent::getDataUtworzenia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataUtworzenia(\DateTimeInterface $dataUtworzenia): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataUtworzenia', [$dataUtworzenia]);

        return parent::setDataUtworzenia($dataUtworzenia);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?bool $status): \App\Entity\Message
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
